### ISSUE TITLE
Singleton MySQLConnector

### ISSUE THREAD

**Issue by derrykid** [Alencaminha/Java-Swing-Store-Management-App#2]
What's your design approach of DAO classes? I notice you close the object connection by: e.g. userDAO `close()` method. 

That way, every time you access to database, you **must create a new MySQLConnector**. I think use singleton, and continuously use the same object in Database connection is a better approach.

**Comment by Alencaminha** [comment]
Hi, @derrykid. The design I used for the DAO classes is pretty much a copy and paste from what my professor showed me at college as an introduction to the project, and I didn't give much thought to refactoring it. As this was just a extension of what I presented to him, and not really a full fletched project for commercial use I don't have much interest in putting more time in this right now. Yet, i very much appreciate you taking your time to pointing out parts of my project I can improve on, and I will think about the implementation of a singleton for database connection the next time I attempt a project like this.
